### ISSUE TITLE
New endpoint

### ISSUE THREAD

**Issue by ourarash** [svlapin/fixer-api#14]
While the base URL can be changed, the default endpoint URL should be updated:

From this link:

https://github.com/fixerAPI/fixer

> 
[The old, deprecated Fixer API will be discontinued on June 1st, 2018]

We are happy to announce the complete relaunch of fixer.io into a more stable, more secure, and much more advanced currency & exchange rate conversion API platform. While the core structure of our API remains unchanged, all users of the legacy Fixer API will be required to sign up for a free API access key and perform a few simple changes to their integration. To learn more about the changes that are required, please jump to the „Required Changes“ section below.

Required Changes to Legacy Integrations (api.fixer.io)

As of March 6th 2018, the legacy Fixer API **(api.fixer.io)** is deprecated and a completely re-engineered API is now accessible at **https://data.fixer.io/api/** The core structure of the old API has remained unchanged, and you will only need to perform a few simple changes to your integration.

**Comment by svlapin** [comment]
Thanks @ourarash and sorry for the delay. Deployed as 1.3.0.
