### ISSUE TITLE
Symbols seems to take string rather than array as per documentation

### ISSUE THREAD

**Issue by timdiacon** [svlapin/fixer-api#23]
`{base: 'GBP', symbols:'GBP,EUR'}`

This returns rates for both currencies

`{base: 'GBP', symbols:['GBP','EUR']}`

This only returns rates for EUR

**Comment by svlapin** [comment]
@timdiacon 
thanks for reporting this, you're [exactly right](https://fixer.io/documentation#latestrates) - rates should be comma separated rather than query-string-encoded array.
I'll try to fix and release a new version ASAP.
