### ISSUE TITLE
request failing due to port :80

### ISSUE THREAD

**Issue by timdiacon** [svlapin/fixer-api#25]
I've got a Vue app using fixer-api, it works perfectly when I run locally but when I deploy to Firebase hosting it's adding port :80 to the request which is causing it to fail.

There is some documentation on request about adding port 80 if a proxy is specified but can't work out how I stop this? Any ideas?

**Comment by svlapin** [comment]
Hey @timdiacon ,
could you provide an example of request modification? What exactly is modified and how?
Posing a link for the
> documentation on request about adding port 80 if a proxy is specified

can be of help too.
