### ISSUE TITLE
Missing Time-Series Endpoint

### ISSUE THREAD

**Issue by moltar** [svlapin/fixer-api#34]
https://fixer.io/documentation#timeseries

**Comment by moltar** [comment]
Can create a PR if you’ll merge it promptly. Thank you.

**Comment by svlapin** [comment]
Hey @moltar , thanks for the update - PRs are always welcome :+1:

**Comment by moltar** [comment]
Sorry, I decided to use a different API.

I will not be contributing a PR.

**Comment by svlapin** [comment]
Implemented in #35 
Published in v2.2.0 (https://github.com/svlapin/fixer-api/releases/tag/v2.2.0)
