### ISSUE TITLE
Uncaught TypeError: fixer.set is not a function

### ISSUE THREAD

**Issue by joylazari** [svlapin/fixer-api#40]
Hi @svlapin 
As the title says, when I try to run a script with fixer I got: `Uncaught TypeError: fixer.set is not a function`.
A `console.log(fixer)` returns an empty object `{}`.

**To Reproduce**
Just the very bare minimum initialization, as per documentation: 
```js
const fixer = require('fixer-api');

fixer.set({ accessKey: process.env.REACT_APP_RATES_API_KEY || '' });
```

I'm trying to implement it inside a fully functional ReactJS app with typescript.
I also tried importing the module with `import fixer from 'fixer-api'` but with no avail.

**Setup:**
 - OS: macOS 11.1
 - Browser: Chrome 87
 - node: v15.5.1
 - npm: 7.3.0
 - yarn: 1.22.10
 - typescript: 4.1.13
 - ts-node: 9.1.1
 - react (JS): 17.0.1

**Comment by svlapin** [comment]
Hey @joylazari , thanks for reporting this.

Given the way default `fixer` instance is currently exported:
https://github.com/svlapin/fixer-api/blob/f61405b319a03ae892a7b7f9c9decd4bf1542110/src/index.ts#L4

looks like you should import the module a bit differently:
```ts
import fixer = require('fixer-api');
```
> When exporting a module using export =, TypeScript-specific import module = require("module") must be used to import the module

(from https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require).

Please let me know if that helps.
