### ISSUE TITLE
HTTP base url causes an error with response status code 301

### ISSUE THREAD

**Issue by onevcat** [svlapin/fixer-api#7]
Fixer.io seems to be using HTTPS as their API entry point (https://api.fixer.io). The original request base url `http://api.fixer.io` will now be redirected with a 301 status code. But fixer-api is considering this is an error.

Maybe we should use 'https://api.fixer.io' as the default base url.

**Comment by svlapin** [comment]
@onevcat 
thanks for reporting this.
Switching default URL to `https` makes sense of course, but current `http` seems to also work fine. I tried to figure out the scenario of getting 301 and had no luck - i.e.
```sh
curl -v http://api.fixer.io/latest
```
results in
```
HTTP/1.1 200 OK
```

Can you elaborate on how do you get `301`? Or is that some upcoming change?

**Comment by onevcat** [comment]
Hi,

Yes, it works fine today. It seems that fixer.io changed the behavior today back to a compatible way.

**Comment by onevcat** [comment]
But I guess it would be also better to consider this situation of 301 or 302, since it could actually happen. : ]

**Comment by onevcat** [comment]
Great to see the fix! But it introduced another issue when getting the request url as I mentioned here: https://github.com/svlapin/fixer-api/pull/8#issuecomment-343672814

I am sorry that I am just new to the world of JS and TS. I wish I could send you a p-r to fix it, but I am not sure about the toolchain now. : [

**Comment by svlapin** [comment]
Thanks for your patience @onevcat 
The fix is published as `1.2.6`, should work fine now.
